"""Explicit PlaylistMembership workflow: validated create -> durable canonical membership.

This is the command boundary for caller-driven PlaylistMembership creation. The caller supplies
explicit canonical Playlist and Track references plus relation data (position, added_at); the
workflow validates them and persists a new canonical PlaylistMembership with an independent
``pm_`` identity generated by the P03.3 canonical ID generator.

It never creates a Playlist or a Track, never matches by name, never derives a ``pm_`` ID from
``(playlist_id, track_id)`` or from position/added_at, and never consumes source occurrence
identity. Source-derived automatic reconciliation (turning an ``IDENTIFIED`` occurrence into a
membership) is out of scope.

Authority boundary
------------------

- ``validate_canonical_id`` enforces the correct entity namespace (``pl_`` / ``trk_``).
- ``CanonicalRepository.load_model`` / ``save_model`` is the durable boundary. ``save_model``
  validates the full model (structural + graph) and persists atomically; a validation failure
  happens before any transaction begins, so a partial membership is impossible.

Idempotency / retry contract
----------------------------

``create_playlist_membership`` is **non-idempotent**. Every call generates a fresh ``pm_`` ID and
inserts one new membership. There is no request/command identity in this slice, and the workflow
does **not** deduplicate on ``(playlist_id, track_id)`` or on position/added_at. A caller that
retries the same logical create will therefore produce a second, distinct canonical membership —
which is the correct behavior when the second call is a legitimate second occurrence of the same
Track. Callers that require idempotency must supply their own request identity and reconcile it
above this boundary; that is out of scope here.
"""

from __future__ import annotations

from copy import deepcopy
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from music_agent.identity import (
    EntityType,
    IdentityValidationError,
    generate_canonical_id,
    validate_canonical_id,
)
from music_agent.repository import CanonicalRepository


class MembershipWorkflowError(ValueError):
    code = "membership_workflow_error"


@dataclass(frozen=True, slots=True)
class MembershipCreationResult:
    membership_id: str
    playlist_id: str
    track_id: str
    position: int
    added_at: str | None


def create_playlist_membership(
    database_path: str | Path,
    *,
    playlist_id: str,
    track_id: str,
    position: int,
    added_at: str | None = None,
) -> MembershipCreationResult:
    """Create one canonical PlaylistMembership referencing an existing Playlist and Track.

    ``playlist_id`` and ``track_id`` must be existing canonical entities of the correct type.
    ``position`` is a non-negative integer; ``added_at`` is a timezone-qualified ISO 8601 string
    or ``None``. Both are relation data, not identity. A new independent ``pm_`` ID is generated
    for the membership, so two calls with the same Playlist and Track produce two distinct
    memberships.
    """
    playlist_id = _require_playlist_id(playlist_id)
    track_id = _require_track_id(track_id)
    position = _require_position(position)
    added_at = _require_added_at(added_at)

    membership_id = generate_canonical_id(EntityType.PLAYLIST_MEMBERSHIP)

    with CanonicalRepository(database_path) as repository:
        model = repository.load_model()
        _require_existing(model, "playlists", EntityType.PLAYLIST, playlist_id)
        _require_existing(model, "tracks", EntityType.TRACK, track_id)
        membership = {
            "id": membership_id,
            "playlist_id": playlist_id,
            "track_id": track_id,
            "position": position,
            "added_at": added_at,
        }
        updated = deepcopy(model)
        updated["playlist_memberships"].append(membership)
        repository.save_model(updated)

    return MembershipCreationResult(
        membership_id, playlist_id, track_id, position, added_at
    )


def _require_playlist_id(value: object) -> str:
    if not isinstance(value, str) or value == "":
        raise MembershipWorkflowError("playlist_id must be a non-empty string")
    try:
        validate_canonical_id(EntityType.PLAYLIST, value)
    except IdentityValidationError as error:
        raise MembershipWorkflowError(f"playlist_id is not a canonical Playlist ID: {error}") from error
    return value


def _require_track_id(value: object) -> str:
    if not isinstance(value, str) or value == "":
        raise MembershipWorkflowError("track_id must be a non-empty string")
    try:
        validate_canonical_id(EntityType.TRACK, value)
    except IdentityValidationError as error:
        raise MembershipWorkflowError(f"track_id is not a canonical Track ID: {error}") from error
    return value


def _require_position(value: object) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise MembershipWorkflowError("position must be an integer")
    if value < 0:
        raise MembershipWorkflowError("position must be non-negative")
    return value


def _require_added_at(value: object) -> str | None:
    if value is None:
        return None
    if not isinstance(value, str) or value == "":
        raise MembershipWorkflowError(
            "added_at must be a timezone-qualified ISO 8601 string or None"
        )
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError as error:
        raise MembershipWorkflowError("added_at must be ISO 8601") from error
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        raise MembershipWorkflowError("added_at must include a timezone")
    return value


def _require_existing(
    model: object,
    collection: str,
    entity_type: EntityType,
    canonical_id: str,
) -> None:
    if not isinstance(model, dict):
        raise MembershipWorkflowError("repository model is invalid")
    entities = model.get(collection)
    if not isinstance(entities, list):
        raise MembershipWorkflowError(f"repository model must contain a {collection} collection")
    if canonical_id not in {entity["id"] for entity in entities}:
        raise MembershipWorkflowError(
            f"{entity_type.value} does not exist: {canonical_id}"
        )
